config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'spotprice.ca',
  :user_name            => 'sudobucks',
  :password             => 't7g6p1jh',
  :authentication       => 'plain',
  :enable_starttls_auto => true  }